### ISSUE TITLE
BSc - Common Subjects

### ISSUE THREAD

**Issue by eduardz1** [MuNuChapterHKN/Eta-Kappa-Notes#1]
# First Year

- [ ] Mathematical analysis I / Analisi matematica I
- [ ] Chemistry / Chimica
- [ ] Computer sciences / Informatica
- [ ] English Language 1st level / Lingua inglese I livello
- [ ] Linear algebra and geometry / Algebra lineare e geometria
- [ ] Physics I / Fisica I

# Second Year

- [ ] Mathematical analysis II / Analisi matematica II
- [ ] Physics II / Fisica II

# Elective courses from "Big Global Challenges" catalogue

- [ ] [Algoritmi e democrazia (Grandi Sfide - Digitale)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEGLM&p_a_acc=2027&p_lang=IT)
- [ ] [Assistenza sanitaria e intelligenza artificiale (Grandi Sfide - Salute)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEOLM&p_a_acc=2027&p_lang=IT)
- [ ] [Benessere digitale (Grandi Sfide - Tecnologie e Umanità)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DELLM&p_a_acc=2027&p_lang=IT)
- [ ] [Bio e nano tecnologie in medicina (Grandi Sfide - Salute)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DECLM&p_a_acc=2027&p_lang=IT)
- [ ] [Città, infrastrutture e cambiamento climatico (Grandi Sfide - Clima)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01CAQLM&p_a_acc=2027&p_lang=IT)
- [ ] [Crisi climatica e bias cognitivi (Grandi Sfide - Clima)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01CACLM&p_a_acc=2027&p_lang=IT)
- [ ] [Cybersecurity and National Defence (Grandi Sfide - Digitale)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEHLM&p_a_acc=2027&p_lang=IT)
- [ ] [Energy transition and society (Grandi Sfide - Energia)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEQLM&p_a_acc=2027&p_lang=IT)
- [ ] [Evidenze, modelli e percezione del cambiamento climatico (Grandi Sfide - Clima)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01BPOLM&p_a_acc=2027&p_lang=IT)
- [ ] [Future of Work (Grandi Sfide - Tecnologie e Umanità)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEKLM&p_a_acc=2027&p_lang=IT)
- [ ] [Genere e tecnica (Grandi Sfide - Tecnologie e Umanità)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DERLM&p_a_acc=2027&p_lang=IT)
- [ ] [Il mare e la transizione verde (Grandi Sfide - Energia)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEDLM&p_a_acc=2027&p_lang=IT)
- [ ] [Infrastrutture intelligenti (Grandi Sfide - Mobilità)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01CAKLM&p_a_acc=2027&p_lang=IT)
- [ ] [Internet e social media: tecnologie e derive della comunicazione in rete (Grandi Sfide - Digitale)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEMLM&p_a_acc=2027&p_lang=IT)
- [ ] [La società della sostenibilità (Grandi Sfide - Clima)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01CZOLM&p_a_acc=2027&p_lang=IT)
- [ ] [Migrations and settlements (Grandi Sfide - Mobilità)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEFLM&p_a_acc=2027&p_lang=IT)
- [ ] [Mobilità urbana sostenibile (Grandi Sfide - Mobilità)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01CAGLM&p_a_acc=2027&p_lang=IT)
- [ ] [Neuroengineering and active aging (Grandi Sfide - Salute)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DENLM&p_a_acc=2027&p_lang=IT)
- [ ] [Politica e tecnica (Grandi Sfide - Digitale)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEILM&p_a_acc=2027&p_lang=IT)
- [ ] [Realtà virtuale e fragilità (Grandi Sfide - Salute)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01CVILM&p_a_acc=2027&p_lang=IT)
- [ ] [Smart city e inclusione (Grandi Sfide - Tecnologie e Umanità)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEJLM&p_a_acc=2027&p_lang=IT)
- [ ] [Sostenibilità e responsabilità (Grandi Sfide - Energia)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEALM&p_a_acc=2027&p_lang=IT)
- [ ] [Storia futura dell'energia (Grandi Sfide - Energia)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEPLM&p_a_acc=2027&p_lang=IT)
- [ ] [The future E-mobility (Grandi Sfide - Mobilità)](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DEBLM&p_a_acc=2027&p_lang=IT)

# Free ECTS credits 3rd year

- [ ] [Calcolo numerico: metodi e software](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01SUNLM&p_a_acc=2027&p_lang=IT)
- [ ] [Energia, progresso e sostenibilità](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01OYZLM&p_a_acc=2027&p_lang=IT)
- [ ] [Etica della Tecnologia](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01HMWLM&p_a_acc=2027&p_lang=IT)
- [ ] [GeoAI: intelligenza artificiale e dati geospaziali](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01OTTLM&p_a_acc=2027&p_lang=IT)
- [ ] [Gestione industriale della qualità](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02BDYLM&p_a_acc=2027&p_lang=IT)
- [ ] [Imprenditorialità e innovazione](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01RMMLM&p_a_acc=2027&p_lang=IT)
- [ ] [Modellazione digitale di impianti](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DYBLM&p_a_acc=2027&p_lang=IT)
- [ ] [Pedagogia dell'intercultura](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DGZLM&p_a_acc=2027&p_lang=IT)
- [ ] [Processi di re-impiego e valorizzazione energetica](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01POSLM&p_a_acc=2027&p_lang=IT)
- [ ] [Processi sostenibili per l'industria alimentare](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01OGXLM&p_a_acc=2027&p_lang=IT)
- [ ] [Psicologia del lavoro e delle organizzazioni](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01GBPLM&p_a_acc=2027&p_lang=IT)
- [ ] [Psicologia del marketing e dei consumi](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DHGLM&p_a_acc=2027&p_lang=IT)
- [ ] [Psicologia e psicopatologia delle organizzazioni](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DHFLM&p_a_acc=2027&p_lang=IT)
- [ ] [Psicologia economica](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01GBQLM&p_a_acc=2027&p_lang=IT)
- [ ] [Storia delle Scienze e delle Tecniche](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01FSWLM&p_a_acc=2027&p_lang=IT)
- [ ] [Strumenti dell'Ingegneria per l'industria 4.0](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01RZWLM&p_a_acc=2027&p_lang=IT)
- [ ] [Tecnologie politiche](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01RTFLM&p_a_acc=2027&p_lang=IT)
- [ ] [Teorie e metodi per la progettazione psicosociale](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DHDLM&p_a_acc=2027&p_lang=IT)
- [ ] [Psicologia ambientale](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DHHLM&p_a_acc=2027&p_lang=IT)
- [ ] [Psicologia sanitaria e psicotraumatologia](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DHALM&p_a_acc=2027&p_lang=IT)
- [ ] [Storia ed estetica delle tecnologie e della musica elettroacustica](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01SBKLM&p_a_acc=2027&p_lang=IT)
- [ ] [Advanced technologies for risk-based decision making](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DYCLM&p_a_acc=2027&p_lang=IT)
- [ ] [Affidabilità, sicurezza e manutenzione per l'azienda](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01QYTLM&p_a_acc=2027&p_lang=IT)
- [ ] [Agri-Tech: Technologies for a sustainable agriculture](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01FGGLM&p_a_acc=2027&p_lang=IT)
- [ ] [Applied signal processing laboratory](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02TUMLM&p_a_acc=2027&p_lang=IT)
- [ ] [Automotive Industry Evolution](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01OGULM&p_a_acc=2027&p_lang=IT)
- [ ] [Cambiamenti climatici e socio economici](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01SANLM&p_a_acc=2027&p_lang=IT)
- [ ] [Company economics](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01OFYLM&p_a_acc=2027&p_lang=IT)
- [ ] [Compatibilità elettromagnetica nell'integrazione dei sistemi](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01QYYLM&p_a_acc=2027&p_lang=IT)
- [ ] [Conflitti tra scienza, tecnologia e umanità](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01HOGLM&p_a_acc=2027&p_lang=IT)
- [ ] [Controllo dei sistemi meccanici](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02EQYLM&p_a_acc=2027&p_lang=IT)
- [ ] [Droni per il rilievo territoriale e architettonico](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01SAOLM&p_a_acc=2027&p_lang=IT)
- [ ] [Elementi di fisica nucleare](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=03IOYLM&p_a_acc=2027&p_lang=IT)
- [ ] [Evoluzione dei veicoli aerospaziali](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01OQDLM&p_a_acc=2027&p_lang=IT)
- [ ] [Generazione fotovoltaica ed eolica di energia elettrica](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01OELLM&p_a_acc=2027&p_lang=IT)
- [ ] [Impianti di cogenerazione](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01QMBLM&p_a_acc=2027&p_lang=IT)
- [ ] [Impostazione progettuale dell'autoveicolo](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01FLXLM&p_a_acc=2027&p_lang=IT)
- [ ] [Inclusive design nelle scienze dell'architettura e dell'ingegneria](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=03SAMLM&p_a_acc=2027&p_lang=IT)
- [ ] [Ingegneria nelle terapie medico-chirurgiche](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01QZQLM&p_a_acc=2027&p_lang=IT)
- [ ] [Introduzione all'informazione e calcolo quantistico](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01UEHLM&p_a_acc=2027&p_lang=IT)
- [ ] [Introduzione alle nanotecnologie](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02JNULM&p_a_acc=2027&p_lang=IT)
- [ ] [Laboratorio di Internet](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01UEJLM&p_a_acc=2027&p_lang=IT)
- [ ] [Modelli e Metodi della Fisica Matematica per l'Ingegneria](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01OTRLM&p_a_acc=2027&p_lang=IT)
- [ ] [Music and multimedia streaming over the Internet](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01OTOLM&p_a_acc=2027&p_lang=IT)
- [ ] [Ottimizzazione per il problem solving](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01QNKLM&p_a_acc=2027&p_lang=IT)
- [ ] [Pedagogia speciale](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DGYLM&p_a_acc=2027&p_lang=IT)
- [ ] [Psicologia dell'apprendimento e della formazione](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01DHELM&p_a_acc=2027&p_lang=IT)
- [ ] [Reti e sistemi complessi: fenomeni fisici e interazioni sociali](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01QFXLM&p_a_acc=2027&p_lang=IT)
- [ ] [Rischio sismico](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01QZJLM&p_a_acc=2027&p_lang=IT)
- [ ] [Sicurezza e legislazione dell'ambiente e del territorio](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01NJALM&p_a_acc=2027&p_lang=IT)
- [ ] [Sistemi di propulsione elettrica per i trasporti](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02NMLLM&p_a_acc=2027&p_lang=IT)
- [ ] [Sperimentazione e progettazione di tecnologie energetiche](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01QMCLM&p_a_acc=2027&p_lang=IT)
- [ ] [Tecnologie per IoT](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01UEILM&p_a_acc=2027&p_lang=IT)
