### ISSUE TITLE
BSc - Computer Engineering

### ISSUE THREAD

**Issue by eduardz1** [MuNuChapterHKN/Eta-Kappa-Notes#2]
# First Year

- [ ] [Mathematical analysis I](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=04KWQLM&p_a_acc=2025&p_lang=IT) / [Analisi matematica I](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=16ACFOA&p_a_acc=2025&p_lang=IT)
- [ ] [Chemistry](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=06KWRLM&p_a_acc=2025&p_lang=IT) / [Chimica](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=15AHMOA&p_a_acc=2025&p_lang=IT)
- [ ] [Computer sciences](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=07JCJLM&p_a_acc=2025&p_lang=IT) / [Informatica](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=14BHDOA&p_a_acc=2025&p_lang=IT)
- [ ] [English Language 1st level](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02MCCLM&p_a_acc=2025&p_lang=IT) / [Lingua inglese I livello](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=07LKIOA&p_a_acc=2025&p_lang=IT)
- [ ] [Linear algebra and geometry](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=03KXTLM&p_a_acc=2025&p_lang=IT) / [Linear algebra and geometry](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=03KXTLM&p_a_acc=2025&p_lang=IT)
- [ ] [Physics I](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=04KXVLM&p_a_acc=2025&p_lang=IT) / [Fisica I](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=17AXOOA&p_a_acc=2025&p_lang=IT)
- [ ] [Programming techniques](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02OJPLM&p_a_acc=2025&p_lang=IT) / [Tecniche di programmazione](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01FYZOA&p_a_acc=2025&p_lang=IT)

# Second Year

- [ ] [Algorithms and data structures](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01URNLM&p_a_acc=2026&p_lang=IT) / [Algoritmi e strutture dati](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=03AAXOA&p_a_acc=2026&p_lang=IT)
- [ ] [Electromagnetism and Circuit theory](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01URLLM&p_a_acc=2026&p_lang=IT) / [Elettromagnetismo e Teoria dei circuiti](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01URKOA&p_a_acc=2026&p_lang=IT)
- [ ] [Introduction to databases](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01RKWLM&p_a_acc=2026&p_lang=IT) / [Basi di dati](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=14AFQOA&p_a_acc=2026&p_lang=IT)
- [ ] [Mathematical analysis II](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=07KXULM&p_a_acc=2026&p_lang=IT) / [Analisi matematica II](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=26ACIOA&p_a_acc=2026&p_lang=IT)
- [ ] [Computer architecture](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02KTMLM&p_a_acc=2026&p_lang=IT) / [Calcolatori elettronici](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=12AGAOA&p_a_acc=2026&p_lang=IT)
- [ ] [Digital Electronics Design](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01GYBLM&p_a_acc=2026&p_lang=IT) / [Progettazione elettronica digitale](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01GYAOA&p_a_acc=2026&p_lang=IT)
- [ ] [Mathematical methods for Computer Science](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01UROLM&p_a_acc=2026&p_lang=IT) /[Metodi matematici per l'ingegneria](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=09BQXOA&p_a_acc=2026&p_lang=IT)

# Third Year

- [ ] [Computer networks](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=08KSILM&p_a_acc=2027&p_lang=IT) / [Reti di calcolatori](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=15CDUOA&p_a_acc=2027&p_lang=IT)
- [ ] [Object oriented programming](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=04JEYOA&p_a_acc=2027&p_lang=IT) / [Programmazione a oggetti](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=09CBIOA&p_a_acc=2027&p_lang=IT)
- [ ] [Operating systems](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=04JEZOA&p_a_acc=2027&p_lang=IT)/ [Sistemi operativi](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=05CJCOA&p_a_acc=2027&p_lang=IT)
- [ ] [Signal analysis and processing](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02OGGOA&p_a_acc=2027&p_lang=IT) / [Teoria ed elaborazione dei segnali](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02MOOOA&p_a_acc=2027&p_lang=IT)
- [ ] [Automatic control](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=06LSLOA&p_a_acc=2027&p_lang=IT) / [Controlli automatici](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=18AKSOA&p_a_acc=2027&p_lang=IT)

# Table A courses

- [ ] [Diritto ed etica della comunicazione](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02JFMLM&p_a_acc=2027&p_lang=IT)

# Table C courses

- [ ] [Analisi e visualizzazione dati](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01GYILM&p_a_acc=2027&p_lang=IT)
- [ ] [Embedded Systems and IoT](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01GYCLM&p_a_acc=2027&p_lang=IT)
- [ ] [Introduzione all'elettronica dei sistemi embedded](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=01GYJLM&p_a_acc=2027&p_lang=IT)
- [ ] [Introduzione alle Applicazioni Web](https://didattica.polito.it/pls/portal30/sviluppo.guide.visualizza?p_cod_ins=02DXULM&p_a_acc=2027&p_lang=IT)
